// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 7: Modify Guest Reservations', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Navigate', async function() {
    // Test name: Navigate
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | css=.MuiSvgIcon-fontSizeLarge > path | 
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge > path")).click()
    // 4 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 5 | click | id=simple-tab-2 | 
    await driver.findElement(By.id("simple-tab-2")).click()
    // 6 | click | css=.MuiTableRow-root:nth-child(3) path | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 7 | selectWindow | handle=${win6926} | 
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(3) path")).click()
    // 8 | click | css=#sb_ifc51 > .tactile-searchbox-input | 
    vars["win6926"] = await waitForWindow(2000)
    // 9 | click | css=#sb_ifc51 > .tactile-searchbox-input | 
    await driver.switchTo().window(vars["win6926"])
    // 10 | click | xpath=//div[@id='directions-searchbox-1']/button | 
    await driver.findElement(By.css("#sb_ifc51 > .tactile-searchbox-input")).click()
    await driver.findElement(By.css("#sb_ifc51 > .tactile-searchbox-input")).click()
    await driver.findElement(By.xpath("//div[@id=\'directions-searchbox-1\']/button")).click()
  })
  it('Cancel User Reservation ', async function() {
    // Test name: Cancel User Reservation 
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | css=.MuiSvgIcon-fontSizeLarge > path | 
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge > path")).click()
    // 4 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 5 | mouseOver | id=simple-tab-2 | 
    {
      const element = await driver.findElement(By.id("simple-tab-2"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 6 | click | id=simple-tab-2 | 
    await driver.findElement(By.id("simple-tab-2")).click()
    // 7 | mouseOut | id=simple-tab-2 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 8 | click | css=.MuiTableRow-root:nth-child(3) > .MuiButton-root | 
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(3) > .MuiButton-root")).click()
    // 9 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 10 | click | id=simple-tab-2 | 
    await driver.findElement(By.id("simple-tab-2")).click()
  })
  it('Review Gym', async function() {
    // Test name: Review Gym
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | linkText=Find a Gym | 
    await driver.findElement(By.linkText("Find a Gym")).click()
    // 4 | click | id=search-zip | 
    await driver.findElement(By.id("search-zip")).click()
    // 5 | type | id=search-zip | 95819
    await driver.findElement(By.id("search-zip")).sendKeys("95819")
    // 6 | click | css=.MuiButton-root | 
    await driver.findElement(By.css(".MuiButton-root")).click()
    // 7 | click | css=.MuiGrid-root:nth-child(8) img | 
    await driver.findElement(By.css(".MuiGrid-root:nth-child(8) img")).click()
    // 8 | click | css=.MuiSvgIcon-fontSizeLarge | 
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge")).click()
    // 9 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 10 | click | id=simple-tab-2 | 
    await driver.findElement(By.id("simple-tab-2")).click()
    // 11 | click | css=.MuiFab-primary > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiFab-primary > .MuiSvgIcon-root")).click()
    // 12 | click | css=.css-dqr9h-MuiRating-label:nth-child(7) | 
    await driver.findElement(By.css(".css-dqr9h-MuiRating-label:nth-child(7)")).click()
    // 13 | type | css=textarea | A great gym!
    await driver.findElement(By.css("textarea")).sendKeys("A great gym!")
    // 14 | click | css=.MuiButton-sizeMedium | 
    await driver.findElement(By.css(".MuiButton-sizeMedium")).click()
    // 15 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 16 | click | id=simple-tab-2 | 
    await driver.findElement(By.id("simple-tab-2")).click()
    // 17 | mouseOver | id=simple-tab-2 | 
    {
      const element = await driver.findElement(By.id("simple-tab-2"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 18 | mouseOut | id=simple-tab-2 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 19 | click | css=.MuiTableRow-root:nth-child(1) > a > .MuiTableCell-root | 
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(1) > a > .MuiTableCell-root")).click()
  })
})
