// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 2: Adding a gym', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Upload Gym', async function() {
    // Test name: Upload Gym
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | waitForElementPresent | linkText=List a Gym | 30000
    await driver.wait(until.elementLocated(By.linkText("List a Gym")), 30000)
    // 4 | click | linkText=List a Gym | 
    await driver.findElement(By.linkText("List a Gym")).click()
    // 5 | waitForElementPresent | id=name | 30000
    await driver.wait(until.elementLocated(By.id("name")), 30000)
    // 6 | click | id=name | 
    await driver.findElement(By.id("name")).click()
    // 7 | type | id=name | Matthew's Gym
    await driver.findElement(By.id("name")).sendKeys("Matthew\'s Gym")
    // 8 | type | id=description | Matt's home gym
    await driver.findElement(By.id("description")).sendKeys("Matt\'s home gym")
    // 9 | click | id=max-guests | 
    await driver.findElement(By.id("max-guests")).click()
    // 10 | type | id=max-guests | 5
    await driver.findElement(By.id("max-guests")).sendKeys("5")
    // 11 | click | id=max-guests | 
    await driver.findElement(By.id("max-guests")).click()
    // 12 | click | id=notes | 
    await driver.findElement(By.id("notes")).click()
    // 13 | type | id=notes | Use code '2112'
    await driver.findElement(By.id("notes")).sendKeys("Use code \'2112\'")
    // 14 | click | id=location-street | 
    await driver.findElement(By.id("location-street")).click()
    // 15 | type | id=location-street | Sacramento Street
    await driver.findElement(By.id("location-street")).sendKeys("Sacramento Street")
    // 16 | type | id=location-city | Sacramento
    await driver.findElement(By.id("location-city")).sendKeys("Sacramento")
    // 17 | type | id=location-state | CA
    await driver.findElement(By.id("location-state")).sendKeys("CA")
    // 18 | type | id=location-zip | 95819
    await driver.findElement(By.id("location-zip")).sendKeys("95819")
    // 19 | click | id=action-tab-1 | 
    await driver.findElement(By.id("action-tab-1")).click()
    // 21 | mouseDown | id=Equipment | 
    {
      const element = await driver.findElement(By.id("Equipment"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 22 | mouseUp | css=#menu- > .MuiBackdrop-root | 
    {
      const element = await driver.findElement(By.css("#menu- > .MuiBackdrop-root"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 24 | click | css=.MuiButtonBase-root:nth-child(7) | 
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(7)")).click()
    // 25 | click | id=equip-details | 
    await driver.findElement(By.id("equip-details")).click()
    // 26 | mouseOver | css=.MuiButton-sizeLarge | 
    {
      const element = await driver.findElement(By.css(".MuiButton-sizeLarge"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 27 | type | id=equip-details | 10-50 lb
    await driver.findElement(By.id("equip-details")).sendKeys("10-50 lb")
    // 28 | click | css=.MuiButton-sizeLarge | 
    await driver.findElement(By.css(".MuiButton-sizeLarge")).click()
    // 29 | click | id=action-tab-2 | 
    await driver.findElement(By.id("action-tab-2")).click()
    // 30 | click | name=mui-87 | 
    await driver.findElement(By.name("mui-87")).click()
    // 31 | click | name=mui-88 | 
    await driver.findElement(By.name("mui-88")).click()
    // 32 | click | name=mui-89 | 
    await driver.findElement(By.name("mui-89")).click()
    // 33 | mouseDown | css=.MuiSelect-select | 
    {
      const element = await driver.findElement(By.css(".MuiSelect-select"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 34 | mouseUp | css=#menu- > .MuiBackdrop-root | 
    {
      const element = await driver.findElement(By.css("#menu- > .MuiBackdrop-root"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 35 | click | css=body | 
    await driver.findElement(By.css("body")).click()
    // 36 | click | css=#menu- .MuiButtonBase-root:nth-child(3) | 
    await driver.findElement(By.css("#menu- .MuiButtonBase-root:nth-child(3)")).click()
    // 37 | mouseOver | id=action-tab-3 | 
    {
      const element = await driver.findElement(By.id("action-tab-3"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 38 | click | id=action-tab-3 | 
    await driver.findElement(By.id("action-tab-3")).click()
    // 39 | mouseOut | id=action-tab-3 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 40 | mouseOver | css=.css-1lwbda4-MuiStack-root path | 
    {
      const element = await driver.findElement(By.css(".css-1lwbda4-MuiStack-root path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 41 | click | css=.css-1lwbda4-MuiStack-root path | 
    await driver.findElement(By.css(".css-1lwbda4-MuiStack-root path")).click()
    // 42 | mouseOut | css=.css-1lwbda4-MuiStack-root path | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 43 | click | css=.MuiIconButton-edgeStart > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root")).click()
    // 44 | click | css=.MuiDayPicker-weekContainer:nth-child(4) > .MuiButtonBase-root:nth-child(3) | 
    await driver.findElement(By.css(".MuiDayPicker-weekContainer:nth-child(4) > .MuiButtonBase-root:nth-child(3)")).click()
    // 45 | click | css=.MuiToggleButton-root:nth-child(2) | 
    await driver.findElement(By.css(".MuiToggleButton-root:nth-child(2)")).click()
    // 46 | click | css=.MuiToggleButton-root:nth-child(4) | 
    await driver.findElement(By.css(".MuiToggleButton-root:nth-child(4)")).click()
    // 47 | click | css=.MuiButtonBase-root:nth-child(6) | 
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6)")).click()
    // 48 | click | css=.css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root | 
    await driver.findElement(By.css(".css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root")).click()
    // 49 | mouseOver | css=.MuiClock-pmButton > .MuiTypography-root | 
    {
      const element = await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 50 | click | css=.MuiClock-pmButton > .MuiTypography-root | 
    await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root")).click()
    // 51 | mouseOut | css=.MuiClock-pmButton > .MuiTypography-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 52 | click | css=.MuiClock-squareMask | 
    await driver.findElement(By.css(".MuiClock-squareMask")).click()
    // 53 | mouseOver | css=.MuiFormControl-root:nth-child(2) .MuiButtonBase-root | 
    {
      const element = await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 54 | click | css=.MuiFormControl-root:nth-child(2) .MuiButtonBase-root | 
    await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiButtonBase-root")).click()
    // 55 | mouseOut | css=.MuiFormControl-root:nth-child(2) .MuiButtonBase-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 56 | click | css=.MuiClock-squareMask | 
    await driver.findElement(By.css(".MuiClock-squareMask")).click()
    // 57 | mouseOver | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 58 | click | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiSvgIcon-root")).click()
    // 59 | mouseOut | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 60 | mouseOver | css=.MuiClock-pmButton > .MuiTypography-root | 
    {
      const element = await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 61 | click | css=.MuiClock-pmButton > .MuiTypography-root | 
    await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root")).click()
    // 62 | mouseOut | css=.MuiClock-pmButton > .MuiTypography-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 63 | click | css=.MuiClock-squareMask | 
    await driver.findElement(By.css(".MuiClock-squareMask")).click()
    // 64 | click | id=hourly-rate | 
    await driver.findElement(By.id("hourly-rate")).click()
    // 65 | mouseDownAt | id=hourly-rate | 12.880615234375,23.29852294921875
    {
      const element = await driver.findElement(By.id("hourly-rate"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 66 | mouseMoveAt | id=hourly-rate | 12.880615234375,23.29852294921875
    {
      const element = await driver.findElement(By.id("hourly-rate"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 67 | mouseUpAt | id=hourly-rate | 12.880615234375,23.29852294921875
    {
      const element = await driver.findElement(By.id("hourly-rate"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 68 | click | id=hourly-rate | 
    await driver.findElement(By.id("hourly-rate")).click()
    // 69 | type | id=hourly-rate | 20
    await driver.findElement(By.id("hourly-rate")).sendKeys("20")
    // 70 | click | id=booking-notice | 
    await driver.findElement(By.id("booking-notice")).click()
    // 71 | type | id=booking-notice | 2
    await driver.findElement(By.id("booking-notice")).sendKeys("2")
    // 72 | mouseDown | id=cancel-notice | 
    {
      const element = await driver.findElement(By.id("cancel-notice"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 73 | mouseUp | id=cancel-notice-label | 
    {
      const element = await driver.findElement(By.id("cancel-notice-label"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 74 | click | css=div:nth-child(4) > .MuiFormControl-root:nth-child(2) | 
    await driver.findElement(By.css("div:nth-child(4) > .MuiFormControl-root:nth-child(2)")).click()
    // 75 | type | id=cancel-notice | 24
    await driver.findElement(By.id("cancel-notice")).sendKeys("24")
    // 76 | click | id=action-tab-0 | 
    await driver.findElement(By.id("action-tab-0")).click()
    // 77 | mouseDown | css=.MuiGrid-root | 
    {
      const element = await driver.findElement(By.css(".MuiGrid-root"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 78 | waitForElementPresent | css=.MuiButtonBase-root:nth-child(6) | 30000
    await driver.wait(until.elementLocated(By.css(".MuiButtonBase-root:nth-child(6)")), 30000)
    // 79 | doubleClick | xpath=//button[contains(.,'REVIEW GYM')] | 
    {
      const element = await driver.findElement(By.xpath("//button[contains(.,\'REVIEW GYM\')]"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
  })
  it('Upload Gym2', async function() {
    // Test name: Upload Gym2
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | linkText=List a Gym | 
    await driver.findElement(By.linkText("List a Gym")).click()
    // 4 | click | id=name | 
    await driver.findElement(By.id("name")).click()
    // 5 | type | id=name | TestGymA
    await driver.findElement(By.id("name")).sendKeys("TestGymA")
    // 6 | click | id=description | 
    await driver.findElement(By.id("description")).click()
    // 7 | type | id=description | testa
    await driver.findElement(By.id("description")).sendKeys("testa")
    // 8 | mouseDownAt | css=.css-19kzrtu | 16.343292236328125,150.74627685546875
    {
      const element = await driver.findElement(By.css(".css-19kzrtu"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 9 | mouseMoveAt | css=.css-19kzrtu | 16.343292236328125,150.74627685546875
    {
      const element = await driver.findElement(By.css(".css-19kzrtu"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | mouseUpAt | css=.css-19kzrtu | 16.343292236328125,150.74627685546875
    {
      const element = await driver.findElement(By.css(".css-19kzrtu"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 11 | click | css=.css-19kzrtu | 
    await driver.findElement(By.css(".css-19kzrtu")).click()
    // 12 | type | id=max-guests | 2
    await driver.findElement(By.id("max-guests")).sendKeys("2")
    // 13 | click | id=notes | 
    await driver.findElement(By.id("notes")).click()
    // 14 | type | id=notes | use code a
    await driver.findElement(By.id("notes")).sendKeys("use code a")
    // 15 | click | id=location-street | 
    await driver.findElement(By.id("location-street")).click()
    // 16 | type | id=location-street | a street
    await driver.findElement(By.id("location-street")).sendKeys("a street")
    // 17 | click | id=location-city | 
    await driver.findElement(By.id("location-city")).click()
    // 18 | type | id=location-city | a city
    await driver.findElement(By.id("location-city")).sendKeys("a city")
    // 19 | click | id=location-state | 
    await driver.findElement(By.id("location-state")).click()
    // 20 | type | id=location-state | CA
    await driver.findElement(By.id("location-state")).sendKeys("CA")
    // 21 | click | id=location-zip | 
    await driver.findElement(By.id("location-zip")).click()
    // 22 | type | id=location-zip | 95819
    await driver.findElement(By.id("location-zip")).sendKeys("95819")
    // 23 | click | id=action-tab-1 | 
    await driver.findElement(By.id("action-tab-1")).click()
    // 24 | mouseDown | id=Equipment | 
    {
      const element = await driver.findElement(By.id("Equipment"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 25 | mouseUp | css=#menu- > .MuiBackdrop-root | 
    {
      const element = await driver.findElement(By.css("#menu- > .MuiBackdrop-root"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 26 | click | css=body | 
    await driver.findElement(By.css("body")).click()
    // 27 | click | css=.MuiButtonBase-root:nth-child(9) | 
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(9)")).click()
    // 28 | click | id=equip-details | 
    await driver.findElement(By.id("equip-details")).click()
    // 29 | mouseOver | css=.MuiButton-root | 
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 30 | type | id=equip-details | dip
    await driver.findElement(By.id("equip-details")).sendKeys("dip")
    // 31 | click | css=.MuiButton-root | 
    await driver.findElement(By.css(".MuiButton-root")).click()
    // 32 | click | id=action-tab-2 | 
    await driver.findElement(By.id("action-tab-2")).click()
    // 33 | mouseOver | name=mui-54 | 
    {
      const element = await driver.findElement(By.name("mui-54"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 34 | click | name=mui-54 | 
    await driver.findElement(By.name("mui-54")).click()
    // 35 | mouseOut | name=mui-54 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 36 | click | name=mui-55 | 
    await driver.findElement(By.name("mui-55")).click()
    // 37 | mouseDown | css=.MuiSelect-select | 
    {
      const element = await driver.findElement(By.css(".MuiSelect-select"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 38 | mouseUp | css=#menu- > .MuiBackdrop-root | 
    {
      const element = await driver.findElement(By.css("#menu- > .MuiBackdrop-root"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 39 | click | css=body | 
    await driver.findElement(By.css("body")).click()
    // 40 | click | css=#menu- .MuiButtonBase-root:nth-child(2) | 
    await driver.findElement(By.css("#menu- .MuiButtonBase-root:nth-child(2)")).click()
    // 41 | mouseOver | id=action-tab-3 | 
    {
      const element = await driver.findElement(By.id("action-tab-3"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 42 | click | id=action-tab-3 | 
    await driver.findElement(By.id("action-tab-3")).click()
    // 43 | mouseOut | id=action-tab-3 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 44 | click | css=.css-1lwbda4-MuiStack-root path | 
    await driver.findElement(By.css(".css-1lwbda4-MuiStack-root path")).click()
    // 45 | mouseOver | css=.MuiIconButton-edgeStart path | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-edgeStart path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 46 | click | css=.MuiIconButton-edgeStart path | 
    await driver.findElement(By.css(".MuiIconButton-edgeStart path")).click()
    // 47 | mouseOut | css=.MuiIconButton-edgeStart path | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 48 | click | css=.MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(4) | 
    await driver.findElement(By.css(".MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(4)")).click()
    // 49 | click | css=.MuiToggleButton-root:nth-child(2) | 
    await driver.findElement(By.css(".MuiToggleButton-root:nth-child(2)")).click()
    // 50 | click | css=.MuiToggleButton-root:nth-child(4) | 
    await driver.findElement(By.css(".MuiToggleButton-root:nth-child(4)")).click()
    // 51 | click | css=.MuiButtonBase-root:nth-child(6) | 
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6)")).click()
    // 52 | click | css=.css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root | 
    await driver.findElement(By.css(".css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root")).click()
    // 53 | mouseOver | css=.css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.css(".css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 54 | mouseOut | css=.css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 55 | mouseOver | css=.MuiClock-pmButton > .MuiTypography-root | 
    {
      const element = await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 56 | click | css=.MuiClock-pmButton > .MuiTypography-root | 
    await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root")).click()
    // 57 | mouseOut | css=.MuiClock-pmButton > .MuiTypography-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 58 | click | css=.MuiClock-squareMask | 
    await driver.findElement(By.css(".MuiClock-squareMask")).click()
    // 59 | mouseOver | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 60 | click | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiSvgIcon-root")).click()
    // 61 | mouseOut | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 62 | mouseOver | css=.MuiClock-pmButton > .MuiTypography-root | 
    {
      const element = await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 63 | click | css=.MuiClock-pmButton > .MuiTypography-root | 
    await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root")).click()
    // 64 | mouseOut | css=.MuiClock-pmButton > .MuiTypography-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 65 | click | css=.MuiClock-squareMask | 
    await driver.findElement(By.css(".MuiClock-squareMask")).click()
    // 66 | click | id=hourly-rate | 
    await driver.findElement(By.id("hourly-rate")).click()
    // 67 | type | id=hourly-rate | 15
    await driver.findElement(By.id("hourly-rate")).sendKeys("15")
    // 68 | click | id=booking-notice | 
    await driver.findElement(By.id("booking-notice")).click()
    // 69 | type | id=booking-notice | 2
    await driver.findElement(By.id("booking-notice")).sendKeys("2")
    // 70 | click | id=cancel-notice | 
    await driver.findElement(By.id("cancel-notice")).click()
    // 71 | type | id=cancel-notice | 12
    await driver.findElement(By.id("cancel-notice")).sendKeys("12")
    // 72 | click | css=.css-13cla7p | 
    await driver.findElement(By.css(".css-13cla7p")).click()
    // 73 | click | id=action-tab-0 | 
    await driver.findElement(By.id("action-tab-0")).click()
    // 74 | mouseOver | css=.MuiButtonBase-root:nth-child(6) | 
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 75 | click | css=.MuiButtonBase-root:nth-child(6) | 
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6)")).click()
    // 76 | click | css=.MuiButtonBase-root > .MuiTypography-root | 
    await driver.findElement(By.css(".MuiButtonBase-root > .MuiTypography-root")).click()
    // 77 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
