// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 9: Modify Profile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update Profile', async function() {
    // Test name: Update Profile
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | mouseOver | css=.MuiSvgIcon-fontSizeLarge > path | 
    {
      const element = await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge > path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 4 | click | css=.MuiSvgIcon-fontSizeLarge > path | 
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge > path")).click()
    // 5 | mouseOut | css=.MuiSvgIcon-fontSizeLarge > path | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 6 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 7 | click | css=html | 
    await driver.findElement(By.css("html")).click()
    // 8 | click | id=simple-tab-3 | 
    await driver.findElement(By.id("simple-tab-3")).click()
    // 9 | click | id=mui-3 | 
    await driver.findElement(By.id("mui-3")).click()
    // 10 | type | id=mui-3 | 2000 E Bidwell St
    await driver.findElement(By.id("mui-3")).sendKeys("2000 E Bidwell St")
    // 11 | click | css=.MuiButton-label | 
    await driver.findElement(By.css(".MuiButton-label")).click()
    // 12 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 13 | click | id=mui-3 | 
    await driver.findElement(By.id("mui-3")).click()
    // 14 | click | id=mui-3 | 
    await driver.findElement(By.id("mui-3")).click()
    // 15 | click | id=mui-3 | 
    await driver.findElement(By.id("mui-3")).click()
    // 16 | type | id=mui-3 | 2775 E Bidwell St
    await driver.findElement(By.id("mui-3")).sendKeys("2775 E Bidwell St")
    // 17 | click | css=.MuiBox-root-21 | 
    await driver.findElement(By.css(".MuiBox-root-21")).click()
    // 18 | mouseOver | css=.MuiButton-label | 
    {
      const element = await driver.findElement(By.css(".MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 19 | click | css=.MuiButton-label | 
    await driver.findElement(By.css(".MuiButton-label")).click()
    // 20 | mouseOut | css=.MuiButton-label | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 21 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
