// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 3: Searching for a gym', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Search Zip', async function() {
    // Test name: Search Zip
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1646x1340 | 
    await driver.manage().window().setRect({ width: 1646, height: 1340 })
    // 3 | click | xpath=//div[@id='root']/div/span/header/div/div/a | 
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/span/header/div/div/a")).click()
    // 4 | click | id=search-zip | 
    await driver.findElement(By.id("search-zip")).click()
    // 5 | type | id=search-zip | 95819
    await driver.findElement(By.id("search-zip")).sendKeys("95819")
    // 6 | click | css=.MuiButton-root | 
    await driver.findElement(By.css(".MuiButton-root")).click()
  })
  it('Search Availability', async function() {
    // Test name: Search Availability
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | linkText=Find a Gym | 
    await driver.findElement(By.linkText("Find a Gym")).click()
    // 4 | click | css=.MuiIconButton-root > .MuiSvgIcon-root > path | 
    await driver.findElement(By.css(".MuiIconButton-root > .MuiSvgIcon-root > path")).click()
    // 5 | click | css=.MuiIconButton-edgeStart > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root")).click()
    // 6 | click | css=.MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(2) | 
    await driver.findElement(By.css(".MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(2)")).click()
    // 7 | click | css=.MuiClock-pmButton > .MuiTypography-root | 
    await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root")).click()
    // 8 | click | css=.MuiClock-squareMask | 
    await driver.findElement(By.css(".MuiClock-squareMask")).click()
    // 9 | click | css=.MuiButton-root | 
    await driver.findElement(By.css(".MuiButton-root")).click()
    // 10 | click | css=.MuiButton-root | 
    await driver.findElement(By.css(".MuiButton-root")).click()
  })
  it('Search Zip and Availability', async function() {
    // Test name: Search Zip and Availability
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1646x1340 | 
    await driver.manage().window().setRect({ width: 1646, height: 1340 })
    // 3 | click | linkText=Find a Gym | 
    await driver.findElement(By.linkText("Find a Gym")).click()
    // 4 | mouseDown | id=search-zip | 
    {
      const element = await driver.findElement(By.id("search-zip"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 5 | mouseUp | id=search-zip-label | 
    {
      const element = await driver.findElement(By.id("search-zip-label"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 6 | click | css=.css-1u3bzj6-MuiFormControl-root-MuiTextField-root:nth-child(1) | 
    await driver.findElement(By.css(".css-1u3bzj6-MuiFormControl-root-MuiTextField-root:nth-child(1)")).click()
    // 7 | mouseOver | css=.MuiIconButton-root > .MuiSvgIcon-root > path | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-root > .MuiSvgIcon-root > path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 8 | type | id=search-zip | 95819
    await driver.findElement(By.id("search-zip")).sendKeys("95819")
    // 9 | click | css=.MuiIconButton-root > .MuiSvgIcon-root > path | 
    await driver.findElement(By.css(".MuiIconButton-root > .MuiSvgIcon-root > path")).click()
    // 10 | mouseOut | css=.MuiIconButton-sizeMedium path | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 11 | mouseOver | css=.MuiIconButton-edgeStart > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | click | css=.MuiIconButton-edgeStart > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root")).click()
    // 13 | mouseOut | css=.MuiIconButton-edgeStart > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 14 | click | css=.MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(2) | 
    await driver.findElement(By.css(".MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(2)")).click()
    // 15 | mouseOver | css=.MuiClock-pmButton | 
    {
      const element = await driver.findElement(By.css(".MuiClock-pmButton"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 16 | mouseOut | css=.MuiClock-pmButton | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 17 | click | css=.MuiClock-pmButton | 
    await driver.findElement(By.css(".MuiClock-pmButton")).click()
    // 18 | click | css=.MuiClock-squareMask | 
    await driver.findElement(By.css(".MuiClock-squareMask")).click()
    // 19 | click | css=.MuiButton-root | 
    await driver.findElement(By.css(".MuiButton-root")).click()
  })
})
