// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 5: Reserving a gym', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Reserve Gym', async function() {
    // Test name: Reserve Gym
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | linkText=Find a Gym | 
    await driver.findElement(By.linkText("Find a Gym")).click()
    // 4 | click | id=search-zip | 
    await driver.findElement(By.id("search-zip")).click()
    // 5 | mouseOver | css=.MuiButton-root | 
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 6 | type | id=search-zip | 95819
    await driver.findElement(By.id("search-zip")).sendKeys("95819")
    // 7 | click | css=.MuiButton-root | 
    await driver.findElement(By.css(".MuiButton-root")).click()
    // 8 | mouseOut | css=.MuiButton-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 9 | mouseOver | css=.MuiGrid-root:nth-child(1) > .MuiPaper-root img | 
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | click | css=.MuiGrid-root:nth-child(1) > .MuiPaper-root img | 
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root img")).click()
    // 11 | mouseOver | css=.MuiIconButton-root > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-root > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | click | css=.MuiIconButton-root > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiIconButton-root > .MuiSvgIcon-root")).click()
    // 13 | mouseOut | css=.MuiIconButton-sizeMedium > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 14 | click | css=.MuiIconButton-edgeStart > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root")).click()
    // 15 | click | css=.MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(4) | 
    await driver.findElement(By.css(".MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(4)")).click()
    // 16 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 17 | type | css=.swal2-range > input | 2
    await driver.findElement(By.css(".swal2-range > input")).sendKeys("2")
    // 18 | click | css=.swal2-range > input | 
    await driver.findElement(By.css(".swal2-range > input")).click()
    // 19 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 20 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 21 | mouseOver | css=.swal2-confirm | 
    {
      const element = await driver.findElement(By.css(".swal2-confirm"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 22 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 23 | click | css=.MuiButtonBase-root:nth-child(1) > .MuiButton-label | 
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(1) > .MuiButton-label")).click()
    // 24 | click | css=.MuiSvgIcon-fontSizeLarge | 
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge")).click()
    // 25 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 26 | click | id=simple-tab-2 | 
    await driver.findElement(By.id("simple-tab-2")).click()
  })
  it('Gym Payment', async function() {
    // Test name: Gym Payment
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | linkText=Find a Gym | 
    await driver.findElement(By.linkText("Find a Gym")).click()
    // 4 | click | id=search-zip | 
    await driver.findElement(By.id("search-zip")).click()
    // 5 | mouseOver | css=.MuiButton-root | 
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 6 | type | id=search-zip | 95819
    await driver.findElement(By.id("search-zip")).sendKeys("95819")
    // 7 | click | css=.MuiButton-root | 
    await driver.findElement(By.css(".MuiButton-root")).click()
    // 8 | mouseOut | css=.MuiButton-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 9 | mouseOver | css=.MuiGrid-root:nth-child(1) > .MuiPaper-root img | 
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | click | css=.MuiGrid-root:nth-child(1) > .MuiPaper-root img | 
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root img")).click()
    // 11 | mouseOver | css=.MuiIconButton-root > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-root > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | click | css=.MuiIconButton-root > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiIconButton-root > .MuiSvgIcon-root")).click()
    // 13 | mouseOut | css=.MuiIconButton-sizeMedium > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 14 | click | css=.MuiIconButton-edgeStart > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root")).click()
    // 15 | click | css=.MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(4) | 
    await driver.findElement(By.css(".MuiDayPicker-weekContainer:nth-child(5) > .MuiButtonBase-root:nth-child(4)")).click()
    // 16 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 17 | type | css=.swal2-range > input | 2
    await driver.findElement(By.css(".swal2-range > input")).sendKeys("2")
    // 18 | click | css=.swal2-range > input | 
    await driver.findElement(By.css(".swal2-range > input")).click()
    // 19 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 20 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 21 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 22 | selectFrame | index=3 | 
    await driver.switchTo().frame(3)
    // 23 | click | id=Field-numberInput | 
    await driver.findElement(By.id("Field-numberInput")).click()
    // 24 | type | id=Field-numberInput | 4242 4242 4242 4242
    await driver.findElement(By.id("Field-numberInput")).sendKeys("4242 4242 4242 4242")
    // 25 | click | id=Field-expiryInput | 
    await driver.findElement(By.id("Field-expiryInput")).click()
    // 26 | type | id=Field-expiryInput | 01 / 30
    await driver.findElement(By.id("Field-expiryInput")).sendKeys("01 / 30")
    // 27 | click | id=Field-cvcInput | 
    await driver.findElement(By.id("Field-cvcInput")).click()
    // 28 | type | id=Field-cvcInput | 123
    await driver.findElement(By.id("Field-cvcInput")).sendKeys("123")
    // 29 | click | id=Field-postalCodeInput | 
    await driver.findElement(By.id("Field-postalCodeInput")).click()
    // 30 | type | id=Field-postalCodeInput | 95819
    await driver.findElement(By.id("Field-postalCodeInput")).sendKeys("95819")
    // 31 | selectFrame | relative=parent | 
    await driver.switchTo().defaultContent()
    // 32 | click | css=.css-10wtahy-MuiStack-root | 
    await driver.findElement(By.css(".css-10wtahy-MuiStack-root")).click()
    // 33 | click | xpath=//span[@id='content']/div/div/form/div[2]/button/span/div | 
    await driver.findElement(By.xpath("//span[@id=\'content\']/div/div/form/div[2]/button/span/div")).click()
  })
})
