// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 8: Modify Host Reservations', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Cancel Host Reservation', async function() {
    // Test name: Cancel Host Reservation
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | css=.MuiSvgIcon-fontSizeLarge > path | 
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge > path")).click()
    // 4 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 5 | mouseOver | id=simple-tab-2 | 
    {
      const element = await driver.findElement(By.id("simple-tab-2"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 6 | click | id=simple-tab-2 | 
    await driver.findElement(By.id("simple-tab-2")).click()
    // 7 | click | id=action-tab-1 | 
    await driver.findElement(By.id("action-tab-1")).click()
    // 8 | click | css=.MuiTableRow-root:nth-child(2) > .MuiButtonBase-root | 
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(2) > .MuiButtonBase-root")).click()
    // 9 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 10 | click | id=simple-tab-2 | 
    await driver.findElement(By.id("simple-tab-2")).click()
    // 11 | click | id=action-tab-1 | 
    await driver.findElement(By.id("action-tab-1")).click()
  })
})
