import React, { Component, useState } from "react";
import { Typography, Box, Button } from "@material-ui/core";
import { NavLink } from "react-router-dom";

class TermsPage extends Component {
    render() { return (
        <Box>
            <div className="help-center-link-pages-items">
                <Typography variant="h3">Terms of Use and Service</Typography>
                <Typography className = "policy-page-update" variant="h5">Last Update: 9/30/2022</Typography>
                
                <span className="terms-page-links">
                    <Typography variant="h6"><NavLink to="/pages/PolicyForHosts" style={{ textDecoration: 'none' }}>Policy for Hosts</NavLink></Typography>
                    <Typography variant="h6"><NavLink to="/pages/PolicyForGymUsers" style={{ textDecoration: 'none' }}>Policy for Gym Users</NavLink></Typography>
                    <Typography variant="h6"><NavLink to="/pages/ContactInfo" style={{ textDecoration: 'none' }}>How can I contact Fit-Inn?</NavLink></Typography>
                    <Typography variant="h6"><NavLink to="/pages/ProtectionAndInsurance" style={{ textDecoration: 'none' }}>Host Liability Insurance/Protection</NavLink></Typography>
                    <Typography variant="h6"><NavLink to="/pages/CommunityGuidelines" style={{ textDecoration: 'none' }}>Community Guidelines</NavLink></Typography>
                </span>

                <Typography className="terms-contents" variant="h5">1. Introduction</Typography>
                <div className="terms-page-links">
                    <Typography variant="h6">1.1 These Terms of Service ("Terms") are a binding legal agreement between you and Fit-Inn that govern your use of the websites, applications, or other interactions with Fit-Inn website that post or include a link to these Terms. By using the Fit-Inn Platform, you acknowledge that you have read, understand, and agree to these Terms. If you use the Fit-Inn Platform on behalf of an entity, you represent and warrant that (1) you are authorized to agree to the Terms on behalf of the entity, and (2) the entity will be bound by the Terms. Fit-Inn's collection and use of personal information in connection with your access to and use of the Platform or the services offered via the Platform is described in our privacy policy.</Typography>
                    <Typography className="terms-contents" variant="h6">1.2 The Fit-Inn Platform offers an internet marketplace that facilitates listing, offering, searching for and renting a gym and its surrounding area or other gym. In these Terms, a registered member of the Fit-Inn Platform ("Member") who lists, offers, or provides a Gym is a "Host" and a person who searches for, rents, or uses a Gym (whether as a Member or not) is a "Guest" or a "Gym User". A Guest (or Gym User) who wants to transact with a Host via the Fit-Inn Platform must also be a Member. The Fit-Inn Platform facilitates transactions between Members whereby a Host grants limited license to a Guest (or Gym User) to enter, occupy, and use a Gym (a "Booking").</Typography>
                    <Typography className="terms-contents" variant="h6">1.3 As the provider of the Fit-Inn Platform, Fit-Inn does not own, control, offer or manage any Gym or Member property. Fit-Inn is not a party to any agreement between Members. Even though Fit-Inn may carry insurance coverage for Hosts, Fit-Inn is not an insurer, nor is Fit-Inn acting as an agent in any capacity for any Member.</Typography>
                </div>

                <Typography className="terms-contents" variant="h5">2. Definitions</Typography>
                <div className="terms-page-links">
                    <Typography className="terms-contents" variant="h6">"Account" means a registered account used by a Member to access and use the Fit-Inn Platform.</Typography>
                    <Typography className="terms-contents" variant="h6">"Applicable Laws and Rules" means applicable local or foreign laws, rules, acts, regulations, subsidiary legislation notices, notifications, circulars, license conditions, directions, requests, requirements, guidelines, directives, codes, information papers, practice notes, demands, guidance, or decisions of any national, state or local government, any agency, exchange, regulatory or self-regulatory body (including, for example, homeowners associations or condominium associations), law enforcement body, court, central bank or tax revenue authority or any other authority whether having the force of law or not (including any intergovernmental agreement between the governments or regulatory authorities of two or more jurisdictions or otherwise), as may be amended from time to time.</Typography>
                    <Typography className="terms-contents" variant="h6">"Agreed Duration" means the duration of a Booking agreed upon by a Host and Guest.</Typography>
                    <Typography className="terms-contents" variant="h6">"Content" means feedback, text, photos, audio, video, and other information or materials that a Member posts, uploads, publishes, submits, or transmits on or using the Fit-Inn Platform.</Typography>
                    <Typography className="terms-contents" variant="h6">"Dispute" means any dispute, claim or controversy arising out of or relating to these Terms or the applicability, breach, termination, validity, enforcement or interpretation thereof, or any use of the Fit-Inn Platform, a Gym, or Content, or any interaction or communication between Members.</Typography>
                    <Typography className="terms-contents" variant="h6">"Guest Fee" means the amount that Fit-Inn charges a Guest for a Booking on the Fit-Inn Platform.</Typography>
                    <Typography className="terms-contents" variant="h6">"Host Fee" means the amount Fit-Inn charges a Host for entering a Booking on the Fit-Inn Platform.</Typography>
                    <Typography className="terms-contents" variant="h6">"Listing" means an offer of a Gym as available for Booking posted on the Fit-Inn Platform.</Typography>
                    <Typography className="terms-contents" variant="h6">"Payment Method" means the payment method associated with an Account, such as a credit card, debit card, bank account or PayPal account.</Typography>
                    <Typography className="terms-contents" variant="h6">"Service Fees" means the sum of the Guest Fee, the Host Fee, and any charges associated with payment collection.</Typography>
                    <Typography className="terms-contents" variant="h6">"Tax" or "Taxes" means direct or indirect taxes, sales taxes, occupancy taxes, lodging taxes, tourist taxes, income taxes, pool taxes, or any other taxes or fees that a Member may be required by Applicable Laws and Rules to include in the Listing price, remit, or report to governmental agencies or other entities.</Typography>
                    <Typography className="terms-contents" variant="h6">"Total Price" means the Gym Fee plus Service Fees and Taxes.</Typography>
                    <Typography className="terms-contents" variant="h6">"Gym Fee" means the amount due by a Guest as consideration for a Booking as provided by a Host, not including Service Fees or Taxes.</Typography>
                </div>

                <Typography className="terms-contents" variant="h5">3. Fit-Inn Platform and Bookings</Typography>
                <div className="terms-page-links">
                    <Typography variant="h6">3.1 Fit-Inn Content</Typography>
                    <Typography variant="subtitle1">The Fit-Inn Platform includes content provided by Fit-Inn that is proprietary to us or that is licensed or authorized for use by us ("Fit-Inn Content") as well as Content provided by Hosts, including text, photos, videos, and other materials.</Typography>

                    <Typography className="terms-contents" variant="h6">3.2 Registration Requirements</Typography>
                    <Typography variant="subtitle1">You must create an Account to access and use many features of the Fit-Inn Platform. Registration is permitted only for legal entities, partnerships, and natural persons who are 21 years of age or older. By creating an Account, you represent and warrant that you are over the age of 21 and not a person or entity prohibited from using the Fit-Inn Platform under Applicable Laws and Rules. You may register directly using the Fit-Inn Platform or by any other official registration process provided by Fit-Inn. You agree to provide accurate, current, and complete information during registration and to keep your Account information up to date. You may not register more than one Account or transfer your Account to someone else.</Typography>

                    <Typography className="terms-contents" variant="h6">3.3 Account Credentials; Verification of Payment or Payout Method</Typography>
                    <Typography variant="subtitle1">You are responsible for maintaining the confidentiality and security of your Account credentials and may not disclose your credentials to any third party. You are responsible and liable for activities conducted through your Account and must immediately notify Fit-Inn if you suspect that your credentials have been lost, stolen, or your Account is otherwise compromised. If and as permitted by Applicable Laws and Rules, we may, but have no obligation to (i) ask you to provide identification or other information; (ii) undertake checks designed to help verify your identity or background; (iii) screen you against third-party databases or other sources and request reports from service providers; (iv) ask you to provide a form of government identification (e.g., driver&apos;s license or passport), your date of birth, your address, and other information; (v) require you to take steps to confirm ownership of your email address, Payment Method(s) or Payout Method(s); and (vi) obtain reports from public records of criminal convictions or sex offender registrations or their local equivalents. If we choose to conduct identity verification on any Member, to the extent permitted by Applicable Laws and Rules, we disclaim warranties of any kind, either express or implied, that such checks will identify prior misconduct by a Member or guarantee that a Member will not engage in misconduct in the future. Fit-Inn reserves the right to terminate, suspend, or limit access to your Account if we are unable to obtain or verify any of this information.</Typography>
                
                    <Typography className="terms-contents" variant="h6">3.4 Background Checks</Typography>
                    <Typography variant="subtitle1">Consistent with Applicable Laws and Rules, Fit-Inn may conduct a background check for all Members at the time of Account creation and annually for continuing Members. When you register an Account, you authorize Fit-Inn to submit your relevant information to law enforcement or third-party agencies for purposes of conducting a background check. By using the Fit-Inn Platform, you certify that you are providing us "written instructions" to obtain a background check on you to determine your eligibility for use of the Fit-Inn Platform. You further instruct us to perform ongoing background checks during your use of the Fit-Inn Platform, as needed, to ensure continued safety of our platform and community of users. You agree to cooperate with and assist Fit-Inn in good faith, and to provide any information we reasonably request, and to take such actions as may be reasonably requested by Fit-Inn with respect to any background check.</Typography>
                
                    <Typography className="terms-contents" variant="h6">3.5 Fit-Inn Does Not Provide Bookings</Typography>
                    <Typography variant="subtitle1">Fit-Inn does not provide, control, manage, offer, deliver, or supply any Bookings. Hosts alone are responsible for their Listings and provisioning of their Bookings. When a Guest requests a Booking and a Host agrees to rent their Gym, the Guest and the Host are entering into a contract directly with each other. We are not, and do not become, a party to or otherwise participate in any contractual relationship between any Guest and any Host.We have no control over and do not guarantee (a) the existence, quality, safety, suitability, or legality of any Gyms, (b) the truth or accuracy of any Host Content or any ratings or reviews posted by Members, or (c) the performance or conduct of any Host or Guest. We do not endorse any Host or Guest, even if a Gym is featured on the Fit-Inn Platform or receives positive ratings or reviews. You should always exercise due diligence and care when deciding whether to communicate, interact with, and engage in any transaction with any Host or Guest.The Fit-Inn Platform may also contain links to websites or resources offered by third parties</Typography>
                
                    <Typography className="terms-contents" variant="h6">3.6 Booking Modifications</Typography>
                    <Typography variant="subtitle1">Members are responsible for any booking modification they agree to make ("Booking Modification"). Members agree to pay any additional amounts, fees, or Taxes associated with any Booking Modification.</Typography>
                </div>
                
                <Typography className="terms-contents" variant="h5">4. General Payment Terms</Typography>
                <div className="terms-page-links">
                    <Typography variant="h6">4.1 General payment terms</Typography>
                    <Typography variant="subtitle1">You authorize Fit-Inn to collect from you amounts due under these Terms, in Fit-Inn's sole discretion, by(i) charging the Payment Method associated with the relevant Booking, or(ii) withholding the amount from your future Payout(s).If any of our charges are rejected from the Payment Method you have indicated as your preferable Payment Method, you authorize us(without notice to you, unless required by Applicable Laws and Rules) to, in our sole discretion: (iii) retry such Payment Method; and(iv) collect from any other Payment Method we have on file for you.Specifically, you authorize Fit-Inn to collect from you:</Typography>
                
                    <Typography className="terms-contents" variant="subtitle1">a. Any amount due to Fit-Inn (e.g., as a result of your Bookings, Booking Modifications, cancellations, or other actions as a Member), including reimbursement for costs prepaid by Fit-Inn on your behalf. Any funds collected by Fit-Inn will set off the amount owed by you to Fit-Inn and extinguish your obligation to Fit-Inn.</Typography>
                    <Typography className="terms-contents" variant="subtitle1">b. Taxes, where applicable.</Typography>
                    <Typography className="terms-contents" variant="subtitle1">c. Any other Service Fees imposed under these Terms.</Typography>
                    <Typography className="terms-contents" variant="subtitle1">In addition to any amount due as provided above, if there are delinquent amounts or chargebacks associated with your Payment Method, you may be charged fees that are incidental to Fit-Inn's collection of these delinquent amounts and chargebacks. Such fees or charges may include attorneys' fees, collection fees, convenience fees or other third-party charges.</Typography>
                
                    <Typography className="terms-contents" variant="h6">4.2 Fees</Typography>
                    <Typography variant="subtitle1">Fit-Inn may charge fees and, if applicable, Taxes to Members for use of the Fit-Inn Platform. Fees or charges may include collection fees, convenience fees, third-party charges or any other fees that may be required to address your Account and are permitted by Applicable Laws and Rules. Except as otherwise expressly provided on the Fit-Inn Platform, Service Fees are non-refundable. Fit-Inn reserves the right to change the Service Fees at any time, and will provide Members notice of current fees. Fee changes will not affect Bookings made before the effective date of the fee change.</Typography>
                
                    <Typography className="terms-contents" variant="h6">4.3 Collections</Typography>
                    <Typography variant="subtitle1">Fit-Inn reserves the right to place you into collections if you fail to timely pay any amounts due from your use of the Platform; collections may be done by Fit-Inn or a third-party on Fit-Inn's behalf. You also agree that we may, at our discretion, send your account to a collection agency, and except where prohibited by Applicable Laws and Rules, recover our reasonable costs of collection from you.</Typography>
                </div>
            </div>
        </Box>
    );}
}
export default TermsPage;