// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Upload Gym', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Upload Gym', async function() {
    // Test name: Upload Gym
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1630x1320 | 
    await driver.manage().window().setRect({ width: 1630, height: 1320 })
    // 3 | click | linkText=List a Gym | 
    await driver.wait(until.elementLocated(By.xpath("//div[@id='root']/div/span/header/div/div/a[2]")));
    await driver.wait(until.elementIsVisible(driver.findElement(By.xpath("//div[@id='root']/div/span/header/div/div/a[2]"))), 5000).click();
    // 6 | click | id=name | 
    await driver.wait(until.elementLocated(By.id('name')));
    await driver.wait(until.elementIsVisible(driver.findElement(By.id('name'))), 5000).click();
    // 7 | type | id=name | Matthew's Gym
    await driver.findElement(By.id("name")).sendKeys("Matthew\'s Gym")
  //   // 8 | type | id=description | Matt's home gym
  //   await driver.findElement(By.id("description")).sendKeys("Matt\'s home gym")
  //   // 9 | click | id=max-guests | 
  //   await driver.findElement(By.id("max-guests")).click()
  //   // 10 | type | id=max-guests | 5
  //   await driver.findElement(By.id("max-guests")).sendKeys("5")
  //   // 11 | click | id=max-guests | 
  //   await driver.findElement(By.id("max-guests")).click()
  //   // 12 | click | id=notes | 
  //   await driver.findElement(By.id("notes")).click()
  //   // 13 | type | id=notes | Use code '2112'
  //   await driver.findElement(By.id("notes")).sendKeys("Use code \'2112\'")
  //   // 14 | click | id=location-street | 
  //   await driver.findElement(By.id("location-street")).click()
  //   // 15 | type | id=location-street | Sacramento Street
  //   await driver.findElement(By.id("location-street")).sendKeys("Sacramento Street")
  //   // 16 | type | id=location-city | Sacramento
  //   await driver.findElement(By.id("location-city")).sendKeys("Sacramento")
  //   // 17 | type | id=location-state | CA
  //   await driver.findElement(By.id("location-state")).sendKeys("CA")
  //   // 18 | mouseOver | id=action-tab-1 | 
  //   {
  //     const element = await driver.findElement(By.id("action-tab-1"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 19 | type | id=location-zip | 95819
  //   await driver.findElement(By.id("location-zip")).sendKeys("95819")
  //   // 20 | click | id=action-tab-1 | 
  //   await driver.findElement(By.id("action-tab-1")).click()
  //   // 21 | mouseOut | id=action-tab-1 | 
  //   {
  //     const element = await driver.findElement(By.CSS_SELECTOR, "body")
  //     await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
  //   }
  //   // 22 | mouseDown | id=Equipment | 
  //   {
  //     const element = await driver.findElement(By.id("Equipment"))
  //     await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
  //   }
  //   // 23 | mouseUp | css=#menu- > .MuiBackdrop-root | 
  //   {
  //     const element = await driver.findElement(By.css("#menu- > .MuiBackdrop-root"))
  //     await driver.actions({ bridge: true }).moveToElement(element).release().perform()
  //   }
  //   // 24 | click | css=body | 
  //   await driver.findElement(By.css("body")).click()
  //   // 25 | click | css=.MuiButtonBase-root:nth-child(7) | 
  //   await driver.findElement(By.css(".MuiButtonBase-root:nth-child(7)")).click()
  //   // 26 | click | id=equip-details | 
  //   await driver.findElement(By.id("equip-details")).click()
  //   // 27 | mouseOver | css=.MuiButton-sizeLarge | 
  //   {
  //     const element = await driver.findElement(By.css(".MuiButton-sizeLarge"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 28 | type | id=equip-details | 10-50 lb
  //   await driver.findElement(By.id("equip-details")).sendKeys("10-50 lb")
  //   // 29 | click | css=.MuiButton-sizeLarge | 
  //   await driver.findElement(By.css(".MuiButton-sizeLarge")).click()
  //   // 30 | click | id=action-tab-2 | 
  //   await driver.findElement(By.id("action-tab-2")).click()
  //   // 31 | click | name=mui-87 | 
  //   await driver.findElement(By.name("mui-87")).click()
  //   // 32 | click | name=mui-88 | 
  //   await driver.findElement(By.name("mui-88")).click()
  //   // 33 | click | name=mui-89 | 
  //   await driver.findElement(By.name("mui-89")).click()
  //   // 34 | mouseDown | css=.MuiSelect-select | 
  //   {
  //     const element = await driver.findElement(By.css(".MuiSelect-select"))
  //     await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
  //   }
  //   // 35 | mouseUp | css=#menu- > .MuiBackdrop-root | 
  //   {
  //     const element = await driver.findElement(By.css("#menu- > .MuiBackdrop-root"))
  //     await driver.actions({ bridge: true }).moveToElement(element).release().perform()
  //   }
  //   // 36 | click | css=body | 
  //   await driver.findElement(By.css("body")).click()
  //   // 37 | click | css=#menu- .MuiButtonBase-root:nth-child(3) | 
  //   await driver.findElement(By.css("#menu- .MuiButtonBase-root:nth-child(3)")).click()
  //   // 38 | mouseOver | id=action-tab-3 | 
  //   {
  //     const element = await driver.findElement(By.id("action-tab-3"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 39 | click | id=action-tab-3 | 
  //   await driver.findElement(By.id("action-tab-3")).click()
  //   // 40 | mouseOut | id=action-tab-3 | 
  //   {
  //     const element = await driver.findElement(By.CSS_SELECTOR, "body")
  //     await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
  //   }
  //   // 41 | mouseOver | css=.css-1lwbda4-MuiStack-root path | 
  //   {
  //     const element = await driver.findElement(By.css(".css-1lwbda4-MuiStack-root path"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 42 | click | css=.css-1lwbda4-MuiStack-root path | 
  //   await driver.findElement(By.css(".css-1lwbda4-MuiStack-root path")).click()
  //   // 43 | mouseOut | css=.css-1lwbda4-MuiStack-root path | 
  //   {
  //     const element = await driver.findElement(By.CSS_SELECTOR, "body")
  //     await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
  //   }
  //   // 44 | click | css=.MuiIconButton-edgeStart > .MuiSvgIcon-root | 
  //   await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root")).click()
  //   // 45 | click | css=.MuiDayPicker-weekContainer:nth-child(4) > .MuiButtonBase-root:nth-child(3) | 
  //   await driver.findElement(By.css(".MuiDayPicker-weekContainer:nth-child(4) > .MuiButtonBase-root:nth-child(3)")).click()
  //   // 46 | click | css=.MuiToggleButton-root:nth-child(2) | 
  //   await driver.findElement(By.css(".MuiToggleButton-root:nth-child(2)")).click()
  //   // 47 | click | css=.MuiToggleButton-root:nth-child(4) | 
  //   await driver.findElement(By.css(".MuiToggleButton-root:nth-child(4)")).click()
  //   // 48 | click | css=.MuiButtonBase-root:nth-child(6) | 
  //   await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6)")).click()
  //   // 49 | click | css=.css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root | 
  //   await driver.findElement(By.css(".css-nen11g-MuiStack-root > .MuiFormControl-root:nth-child(1) .MuiSvgIcon-root")).click()
  //   // 50 | mouseOver | css=.MuiClock-pmButton > .MuiTypography-root | 
  //   {
  //     const element = await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 51 | click | css=.MuiClock-pmButton > .MuiTypography-root | 
  //   await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root")).click()
  //   // 52 | mouseOut | css=.MuiClock-pmButton > .MuiTypography-root | 
  //   {
  //     const element = await driver.findElement(By.CSS_SELECTOR, "body")
  //     await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
  //   }
  //   // 53 | click | css=.MuiClock-squareMask | 
  //   await driver.findElement(By.css(".MuiClock-squareMask")).click()
  //   // 54 | mouseOver | css=.MuiFormControl-root:nth-child(2) .MuiButtonBase-root | 
  //   {
  //     const element = await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiButtonBase-root"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 55 | click | css=.MuiFormControl-root:nth-child(2) .MuiButtonBase-root | 
  //   await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiButtonBase-root")).click()
  //   // 56 | mouseOut | css=.MuiFormControl-root:nth-child(2) .MuiButtonBase-root | 
  //   {
  //     const element = await driver.findElement(By.CSS_SELECTOR, "body")
  //     await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
  //   }
  //   // 57 | click | css=.MuiClock-squareMask | 
  //   await driver.findElement(By.css(".MuiClock-squareMask")).click()
  //   // 58 | mouseOver | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
  //   {
  //     const element = await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiSvgIcon-root"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 59 | click | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
  //   await driver.findElement(By.css(".MuiFormControl-root:nth-child(2) .MuiSvgIcon-root")).click()
  //   // 60 | mouseOut | css=.MuiFormControl-root:nth-child(2) .MuiSvgIcon-root | 
  //   {
  //     const element = await driver.findElement(By.CSS_SELECTOR, "body")
  //     await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
  //   }
  //   // 61 | mouseOver | css=.MuiClock-pmButton > .MuiTypography-root | 
  //   {
  //     const element = await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 62 | click | css=.MuiClock-pmButton > .MuiTypography-root | 
  //   await driver.findElement(By.css(".MuiClock-pmButton > .MuiTypography-root")).click()
  //   // 63 | mouseOut | css=.MuiClock-pmButton > .MuiTypography-root | 
  //   {
  //     const element = await driver.findElement(By.CSS_SELECTOR, "body")
  //     await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
  //   }
  //   // 64 | click | css=.MuiClock-squareMask | 
  //   await driver.findElement(By.css(".MuiClock-squareMask")).click()
  //   // 65 | click | id=hourly-rate | 
  //   await driver.findElement(By.id("hourly-rate")).click()
  //   // 66 | mouseDownAt | id=hourly-rate | 12.880615234375,23.29852294921875
  //   {
  //     const element = await driver.findElement(By.id("hourly-rate"))
  //     await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
  //   }
  //   // 67 | mouseMoveAt | id=hourly-rate | 12.880615234375,23.29852294921875
  //   {
  //     const element = await driver.findElement(By.id("hourly-rate"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 68 | mouseUpAt | id=hourly-rate | 12.880615234375,23.29852294921875
  //   {
  //     const element = await driver.findElement(By.id("hourly-rate"))
  //     await driver.actions({ bridge: true }).moveToElement(element).release().perform()
  //   }
  //   // 69 | click | id=hourly-rate | 
  //   await driver.findElement(By.id("hourly-rate")).click()
  //   // 70 | type | id=hourly-rate | 20
  //   await driver.findElement(By.id("hourly-rate")).sendKeys("20")
  //   // 71 | click | id=booking-notice | 
  //   await driver.findElement(By.id("booking-notice")).click()
  //   // 72 | type | id=booking-notice | 2
  //   await driver.findElement(By.id("booking-notice")).sendKeys("2")
  //   // 73 | mouseDown | id=cancel-notice | 
  //   {
  //     const element = await driver.findElement(By.id("cancel-notice"))
  //     await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
  //   }
  //   // 74 | mouseUp | id=cancel-notice-label | 
  //   {
  //     const element = await driver.findElement(By.id("cancel-notice-label"))
  //     await driver.actions({ bridge: true }).moveToElement(element).release().perform()
  //   }
  //   // 75 | click | css=div:nth-child(4) > .MuiFormControl-root:nth-child(2) | 
  //   await driver.findElement(By.css("div:nth-child(4) > .MuiFormControl-root:nth-child(2)")).click()
  //   // 76 | type | id=cancel-notice | 24
  //   await driver.findElement(By.id("cancel-notice")).sendKeys("24")
  //   // 77 | click | css=.MuiButton-root | 
  //   await driver.findElement(By.css(".MuiButton-root")).click()
  //   // 78 | click | css=.MuiButton-text | 
  //   await driver.findElement(By.css(".MuiButton-text")).click()
  //   // 79 | assertAlert | Gym Submitted | 
  //   assert(await driver.switchTo().alert().getText() == "Gym Submitted")
  //   // 80 | mouseOver | id=action-tab-1 | 
  //   {
  //     const element = await driver.findElement(By.id("action-tab-1"))
  //     await driver.actions({ bridge: true }).moveToElement(element).perform()
  //   }
  //   // 81 | mouseOut | id=action-tab-1 | 
  //   {
  //     const element = await driver.findElement(By.CSS_SELECTOR, "body")
  //     await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
  //   }
  })
})