// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Upload Gym', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Upload Gym', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1630, height: 1320 })

    await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge")).click()
    await driver.findElement(By.xpath("//div[@id=\'menu-appbar\']/div[3]/ul/li/a")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("div > svg")).click()
    vars["win6585"] = await waitForWindow(2000)

    await driver.wait(until.elementLocated(By.linkText("List a Gym")), 30000)
    await driver.findElement(By.linkText("List a Gym")).click()
    await driver.wait(until.elementLocated(By.id("name")), 30000)
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Matthew\'s Gym")
  })
})